### ISSUE TITLE
setup.py only works with ZCU111 RFSoC Board

### ISSUE THREAD

**Issue by plysaght** [strath-sdr/rfsoc_sam#5]
The following does not work for XUPRFSoC board ...
```python
# check whether board is supported
def check_env():
    if not board == 'ZCU111':
        raise ValueError("Board {} is not supported.".format(board))
```
I get this error when trying to PIP install on the XUPRFSOC board ...
```console
Collecting git+https://github.com/strath-sdr/rfsoc_sam.git
  Cloning https://github.com/strath-sdr/rfsoc_sam.git to /tmp/pip-req-build-d1seet5o
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-d1seet5o/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-d1seet5o/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z7ldtg1k
         cwd: /tmp/pip-req-build-d1seet5o/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-d1seet5o/setup.py", line 35, in <module>
        check_env()
      File "/tmp/pip-req-build-d1seet5o/setup.py", line 16, in check_env
        raise ValueError("Board {} is not supported.".format(board))
    ValueError: Board XUPRFSOC is not supported.
    ----------------------------------------
```

**Comment by dnorthcote** [comment]
Closing as issue relates to wrong repository.
